export const shelters = [
    { name: 'Adams Street Educational Campus', address: '283 Adams Street' },
    { name: 'Aviation HS', address: '45-30 36 Street' },
    { name: 'Brooklyn Tech HS', address: '29 Ft Greene Place' },
    { name: 'Clara Barton HS', address: '901 Classon Avenue' },
    { name: 'Clinton School', address: '10 E 15 Street' },
    { name: 'Forest Hills HS', address: '67-01 110 Street' },
    { name: 'Frank Sinatra HS', address: '35-12 35Th Avenue' },
    { name: 'George Washington Educational Campus', address: '549 Audobon Avenue' },
    { name: 'Grover Cleveland HS', address: '21-27 Himrod Street' },
    { name: 'Hillcrest HS', address: '160-05 Highland Avenue' },
    { name: "HS of Law, Gov't and Justice", address: '244 E 163 Street' },
    { name: 'HS of Teaching, Lib Arts and Sci', address: '74-20 Commonwealth Blvd' },
    { name: 'IS - HS 362', address: '921 E 228 Street' },
    { name: 'IS 118', address: '154 W 93 Street' },
    { name: 'IS 131', address: '100 Hester Street' },
    { name: 'IS 145', address: '33-34 80 Street' },
    { name: 'IS 158', address: '800 Home Street' },
    { name: 'IS 2', address: '655 Parkside Avenue' },
    { name: 'IS 201', address: '730 Bryant Avenue' },
    { name: 'IS 227', address: '6500 16 Avenue' },
    { name: 'IS 25', address: '34-65 192 Street' },
    { name: 'IS 324', address: '800 Gates Avenue' },
    { name: 'IS 383', address: '1300 Greene Avenue' },
    { name: 'IS 391', address: '2225 Webster Avenue' },
    { name: 'IS 391', address: '790 East New York Avenue' },
    { name: 'IS 51', address: '20 Houston Street' },
    { name: 'IS 55', address: '2021 Bergen Street' },
    { name: 'IS 74', address: '61-15 Oceania Street' },
    { name: 'IS 90', address: '21 Jumel Place' },
    { name: 'Jerome Parker Campus', address: '100 Essex Drive' },
    { name: 'John Jay Educational Campus', address: '237 7th Avenue' },
    { name: 'Martin Luther King Jr. HS', address: '122 Amsterdam Avenue' },
    { name: 'Midtown East Campus (PS 59)', address: '233 E 56 Street' },
    { name: 'MS - HS 141', address: '660 W 237 Street' },
    { name: 'Petrides Complex', address: '715 Ocean Terrace' },
    { name: 'PS - IS 210', address: '501-503 W 152 Street' },
    { name: 'PS - IS 218', address: '1220 Gerard Avenue' },
    { name: 'PS - IS 268', address: '92-07 175 Street' },
    { name: 'PS - IS 30', address: '7002 4 Avenue' },
    { name: 'PS 100', address: '111-11 118 Street' },
    { name: 'PS 102', address: '1827 Archer Street' },
    { name: 'PS 125', address: '425 W 123 Street' },
    { name: 'PS 132', address: '1245 Washington Avenue' },
    { name: 'PS 145', address: '100 Noll Street' },
    { name: 'PS 20', address: '142-30 Barclay Avenue' },
    { name: 'PS 207', address: '40-20 100 Street' },
    { name: 'PS 211', address: '1919 Prospect Avenue' },
    { name: 'PS 226', address: '6006 23 Avenue' },
    { name: 'PS 239', address: '17-15 Weirfield Street' },
    { name: 'PS 24', address: '427 38 Street' },
    { name: 'PS 249', address: '18 Marlborough Road' },
    { name: 'PS 306', address: '40 West Tremont Avenue' },
    { name: 'PS 327', address: '111 Bristol Street' },
    { name: 'PS 56', address: '250 Kramer Avenue' },
    { name: 'PS 58', address: '72-24 Grand Avenue' },
    { name: 'PS 7', address: '858 Jamaica Avenue' },
    { name: 'PS 92', address: '222 W 134 Street' },
    { name: 'Ralph McKee HS', address: '290 St Marks Place' },
    { name: 'Townsend Harris HS', address: '149-11 Melbourne Avenue' },
    { name: 'Walton HS', address: '2780 Reservoir Avenue' },
  ]

export const clintonInventory = [
  {item: "Pork - Backs - Boneless", quantity: 49 },
  {item: "Limes", quantity: 89 },
  {item: "Wine - Jafflin Bourgongone", quantity: 20 },
  {item: "Peach - Fresh", quantity: 22 },
  {item: "Chocolate - White", quantity: 28 },
  {item: "Ginger - Fresh", quantity: 85 },
  {item: "Appetizer - Spring Roll, Veg", quantity: 21 },
  {item: "Allspice - Jamaican", quantity: 34 },
  {item: "Cheese - Feta", quantity: 25 },
  {item: "Bay Leaf", quantity: 16 },
  {item: "Spoon - Soup, Plastic", quantity: 34 },
  {item: "Bread - Bistro Sour", quantity: 69 },
  {item: "Beef - Flank Steak", quantity: 35 },
  {item: "Petit Baguette", quantity: 47 },
  {item: "Tart - Lemon", quantity: 83 },
  {item: "Vaccum Bag - 14x20", quantity: 14 },
  {item: "Gooseberry", quantity: 69 },
  {item: "Rice - Brown", quantity: 15 },
  {item: "Beets", quantity: 54 },
  {item: "Wine - Fino Tio Pepe Gonzalez", quantity: 2 },
  {item: "Bread Bowl Plain", quantity: 21 },
  {item: "Pate Pans Yellow", quantity: 25 },
  {item: "Amaretto", quantity: 36 },
  {item: "Mousse - Mango", quantity: 93 },
  {item: "Curry Powder", quantity: 72 },
  {item: "Creme De Menth - White", quantity: 9 },
  {item: "Trout - Hot Smkd, Dbl Fillet", quantity: 76 },
  {item: "Wine - Duboeuf Beaujolais", quantity: 67 },
  {item: "Breakfast Quesadillas", quantity: 56 },
  {item: "Bread - Triangle White", quantity: 76 },
  {item: "Soup Campbells Beef With Veg", quantity: 14 },
  {item: "Squash - Sunburst", quantity: 70 },
  {item: "Garbage Bags - Black", quantity: 2 },
  {item: "Wasabi Powder", quantity: 67 },
  {item: "Scallops - In Shell", quantity: 53 },
  {item: "Lemonade - Kiwi, 591 Ml", quantity: 94 },
  {item: "Hold Up Tool Storage Rack", quantity: 88 },
  {item: "Tabasco Sauce, 2 Oz", quantity: 99 },
  {item: "Honey - Comb", quantity: 15 },
  {item: "Muffins - Assorted", quantity: 55 },
  {item: "Beer - Blue", quantity: 58 },
  {item: "Scallop - St. Jaques", quantity: 36 },
  {item: "Pasta - Orecchiette", quantity: 74 },
  {item: "Milk - 2%", quantity: 100 },
  {item: "Coffee - Beans, Whole", quantity: 44 },
  {item: "Broom Handle", quantity: 48 },
  {item: "Mcguinness - Blue Curacao", quantity: 48 }
  ]